// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdaybSh16pYPV8DdIvc6RFJWV_Bhpdt8',
    appId: '1:351273690407:web:06f77cb1dad12df010b502',
    messagingSenderId: '351273690407',
    projectId: 'bus-chatapp',
    authDomain: 'bus-chatapp.firebaseapp.com',
    storageBucket: 'bus-chatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduMJ9eS-wc1Cm0VlENeaRpcxXuYXcd_s',
    appId: '1:351273690407:android:449a6044d6b0032410b502',
    messagingSenderId: '351273690407',
    projectId: 'bus-chatapp',
    storageBucket: 'bus-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUp2o2za9F6oWTky2e3RLY766oqPhV48A',
    appId: '1:351273690407:ios:bcf89cfa12769c3010b502',
    messagingSenderId: '351273690407',
    projectId: 'bus-chatapp',
    storageBucket: 'bus-chatapp.appspot.com',
    androidClientId:
        '351273690407-7otnhpk8l61gt582d5pbsqj2a1gavf83.apps.googleusercontent.com',
    iosClientId:
        '351273690407-rmf6som0l22fsgvgk70scp95a1ds97dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUp2o2za9F6oWTky2e3RLY766oqPhV48A',
    appId: '1:351273690407:ios:a3fb9efa2ac4f91d10b502',
    messagingSenderId: '351273690407',
    projectId: 'bus-chatapp',
    storageBucket: 'bus-chatapp.appspot.com',
    androidClientId:
        '351273690407-7otnhpk8l61gt582d5pbsqj2a1gavf83.apps.googleusercontent.com',
    iosClientId:
        '351273690407-cqeap0k5965n3g5kd3e267dg59f8cgom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
